- name: supervisor from pip
  pip: name=supervisor
 
- name: make directories
  file:
    path=/root/local/supervisord/
    state=directory
 
- name: clone init scripts
  git:
    repo=git://github.com/Supervisor/initscripts.git
    dest=/root/local/supervisord/initscripts
 
- name: make directories
  file:
    path=/etc/supervisord/conf.d
    state=directory
 
- name: copy supervisord.conf
  copy:
    src=supervisord.conf
    dest=/etc/supervisord.conf
 
- name: copy initscript
  command:
    cp /root/local/supervisord/initscripts/redhat-init-jkoppe /etc/init.d/supervisord
    creates=/etc/init.d/supervisord
 
- name: copy sysconfig
  command:
    cp /root/local/supervisord/initscripts/redhat-sysconfig-jkoppe /etc/sysconfig/supervisord
    creates=/etc/sysconfig/supervisord
 
- name: start supervisord
  service: name=supervisord enabled=yes state=started
